export const data = [
  [
    {
      id: "1A",
      title: "ABC",
      description: "Posters",
      Qty: "1",
      unit: "45",
      price: "4500",
    },
    {
      id: "1B",
      title: "XYZ",
      description: "Asset Marking",
      Qty: "7",
      unit: "1272",
      price: "8552",
    },
    {
      id: "1C",
      title: "LMN",
      description: "Signages",
      Qty: "12",
      unit: "19",
      price: "1900",
    },
    {
      id: "1D",
      title: "RST",
      description: "Floor graphics",
      Qty: "18",
      unit: "1",
      price: "3800",
    },
  ],
  [
    {
      id: "2A",
      title: "ABC",
      description: "Posters",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
    {
      id: "2B",
      title: "BCD",
      description: "Posters",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
    {
      id: "2C",
      title: "QRS",
      description: "Signages 2",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
    {
      id: "2D",
      title: "DEF",
      description: "Floor Graphics",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
    {
      id: "2E",
      title: "ABC",
      description: "Posters",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
    {
      id: "2F",
      title: "BCD",
      description: "Posters",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
    {
      id: "2G",
      title: "QRS",
      description: "Signages 2",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
    {
      id: "2H",
      title: "DEF",
      description: "Floor Graphics",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
    {
      id: "2I",
      title: "ABC",
      description: "Posters",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
    {
      id: "2J",
      title: "BCD",
      description: "Posters",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
    {
      id: "2K",
      title: "QRS",
      description: "Signages 2",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
    {
      id: "2L",
      title: "DEF",
      description: "Floor Graphics",
      Qty: "12",
      unit: "122",
      price: "1200",
    },
  ],
];
